# Generated by Django 4.0.3 on 2022-09-06 11:01

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='oldcasemaster',
            name='document_ma_vector__b1d8c6_gin',
        ),
        migrations.RenameField(
            model_name='oldcasemaster',
            old_name='vector_column',
            new_name='search_vector',
        ),
        migrations.AddIndex(
            model_name='oldcasemaster',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['search_vector'], name='document_ma_search__fcccdc_gin'),
        ),

        migrations.RunSQL(
            sql="""
            CREATE TRIGGER search_vector_trigger
            BEFORE INSERT OR UPDATE OF 
                case_no, 
                disposal_bench_code, 
                case_year, 
                first_petitioner,
                first_respondent,
                additional_petitioner,
                additional_respondent,
                judge_name,
                petitioner_counsel,
                respondent_counsel,
                district,
                search_vector
            ON document_management_oldcasemaster
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english',                 
                case_no, 
                disposal_bench_code, 
                case_year, 
                first_petitioner,
                first_respondent,
                additional_petitioner,
                additional_respondent,
                judge_name,
                petitioner_counsel,
                respondent_counsel,
                district
            );
            UPDATE document_management_oldcasemaster SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS search_vector_trigger
            ON document_management_oldcasemaster;
            """,
        ),

    ]
