# Generated by Django 4.0.3 on 2022-09-07 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_management', '0002_remove_oldcasemaster_document_ma_vector__b1d8c6_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldcasemaster',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_entry_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oldcasemaster',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
