# Generated by Django 4.0.3 on 2022-09-07 09:14

from django.db import migrations, models
import document_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0003_oldcasemaster_approved_by_oldcasemaster_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldcasedocument',
            name='document_url',
            field=models.FileField(upload_to=document_management.models.get_old_case_document_upload_path),
        ),
    ]
