# Generated by Django 4.0.3 on 2022-09-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0006_rename_filing_date_oldcasemaster_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldcasemaster',
            name='approval_date',
            field=models.DateField(null=True),
        ),
    ]
