# Generated by Django 4.0.3 on 2022-09-16 06:05

from django.db import migrations, models
import document_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0007_oldcasemaster_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldcasemaster',
            name='approval_remarks',
            field=models.CharField(blank=True, default='', max_length=1028, null=True),
        ),
        migrations.AlterField(
            model_name='oldcasedocument',
            name='document_url',
            field=models.FileField(upload_to=document_management.models.get_old_case_document_upload_path, validators=[document_management.models.validate_file_extension]),
        ),
    ]
