# Generated by Django 4.0.3 on 2022-09-26 16:33

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import document_management.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_management', '0008_oldcasemaster_approval_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldcasedocument',
            name='document_url',
            field=models.FileField(upload_to=document_management.models.get_new_case_document_upload_path, validators=[document_management.models.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='NewCaseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_unique_id', models.CharField(max_length=512, unique=True)),
                ('case_no', models.CharField(max_length=512)),
                ('disposal_bench_code', models.CharField(max_length=128, null=True)),
                ('case_year', models.CharField(max_length=4)),
                ('first_petitioner', models.CharField(max_length=256)),
                ('first_respondent', models.CharField(max_length=256)),
                ('additional_petitioner', models.CharField(max_length=1024, null=True)),
                ('additional_respondent', models.CharField(max_length=1024, null=True)),
                ('judge_name', models.CharField(max_length=256, null=True)),
                ('petitioner_counsel', models.CharField(max_length=128, null=True)),
                ('respondent_counsel', models.CharField(max_length=128, null=True)),
                ('district', models.CharField(max_length=32, null=True)),
                ('registration_date', models.DateField()),
                ('disposal_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateField(null=True)),
                ('approval_remarks', models.CharField(blank=True, default='', max_length=1028, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_case_data_entry_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_case_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_case_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='newcasemaster',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='document_ma_search__4f5803_gin'),
        ),
    ]
