# Generated by Django 4.0.3 on 2022-09-26 16:36

from django.db import migrations, models
import django.db.models.deletion
import document_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0009_alter_oldcasedocument_document_url_newcasemaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldcasedocument',
            name='document_url',
            field=models.FileField(upload_to=document_management.models.get_old_case_document_upload_path, validators=[document_management.models.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='NewCaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_url', models.FileField(upload_to=document_management.models.get_new_case_document_upload_path, validators=[document_management.models.validate_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_related_case', to='document_management.oldcasemaster')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_related_type', to='document_management.documenttype')),
            ],
        ),
    ]
