# Generated by Django 4.0.3 on 2022-10-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0010_alter_oldcasedocument_document_url_newcasedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcasedocument',
            name='case_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_related_case', to='document_management.newcasemaster'),
        ),
    ]
