# Generated by Django 4.0.3 on 2022-10-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0011_alter_newcasedocument_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcasemaster',
            name='petitioner_counsel',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='newcasemaster',
            name='respondent_counsel',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='oldcasemaster',
            name='petitioner_counsel',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='oldcasemaster',
            name='respondent_counsel',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
