# Generated by Django 4.0.3 on 2022-10-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0012_alter_newcasemaster_petitioner_counsel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldcasemaster',
            name='additional_petitioner',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='oldcasemaster',
            name='additional_respondent',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='oldcasemaster',
            name='judge_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='oldcasemaster',
            name='petitioner_counsel',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='oldcasemaster',
            name='respondent_counsel',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
