# Generated by Django 4.0.3 on 2022-09-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_complex_department_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='employee_id',
            new_name='employee_idxx',
        ),
    ]
