# Generated by Django 4.0.3 on 2022-09-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_employee_idxxx_userprofile_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designation_isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
