# Generated by Django 4.0.3 on 2022-09-08 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_designation_designation_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designationallocation',
            name='employee_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
