# Generated by Django 4.0.3 on 2022-09-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_designationallocation_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee_isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
