# Generated by Django 4.0.3 on 2022-09-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_employee_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
