# Generated by Django 4.0.3 on 2022-09-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_employee_id_userprofile_employee_idxx'),
        ('accounts', '0009_userprofile_employee_name'),
    ]

    operations = [
    ]
